import type { PhoneProduct } from '@/models/product'

export const phoneCatalog: PhoneProduct[] = [
  {
    id: 'apple-iphone-15-pro-256',
    slug: 'iphone-15-pro-256-natural',
    brand: 'Apple',
    name: 'iPhone 15 Pro',
    heroTitle: 'Titanium feel, flagship speed, clean pre-owned finish.',
    shortDescription: 'Grade A+ iPhone 15 Pro with strong battery health, premium finish, and same-day setup support.',
    longDescription:
      'A polished Apple-like buying flow starts with a device that already feels sorted. This Grade A+ iPhone 15 Pro ships with deep inspection, healthy battery, and premium packaging for buyers who want pro performance without paying launch pricing.',
    category: 'Pro',
    storage: '256GB',
    color: 'Natural Titanium',
    grade: 'A+',
    batteryHealth: 91,
    launchYear: 2023,
    price: 23990000,
    originalPrice: 31990000,
    monthlyPrice: 1999000,
    rating: 4.9,
    reviewCount: 128,
    featured: true,
    badge: 'Best seller',
    finish: 'Titanium frame with matte glass',
    display: '6.1-inch Super Retina XDR',
    chipset: 'A17 Pro',
    camera: '48MP main + 3x telephoto',
    warranty: '12-month hardware warranty',
    stockLabel: 'Ready to ship',
    maxTradeIn: 17500000,
    gradient: 'linear-gradient(135deg, #f6f4ef 0%, #d9d1c5 42%, #7b7166 100%)',
    accessories: ['USB-C cable', 'QC report', 'Battery health certificate', 'Setup guide'],
    summaryBullets: ['Battery health 91%', 'No face-up scratches', 'Unlocked for all carriers'],
    highlightBullets: [
      'Full cosmetic grading with macro check on frame, glass, and camera ring.',
      'Apple-style setup support: data migration guidance and activation checklist.',
      'Low-latency gaming and creator-ready video pipeline for daily premium use.',
    ],
    specs: [
      { label: 'Battery', value: '91% health' },
      { label: 'Security', value: 'Face ID' },
      { label: 'Port', value: 'USB-C' },
      { label: 'Frame', value: 'Titanium' },
      { label: 'Video', value: '4K ProRes ready' },
      { label: 'Connectivity', value: '5G + Wi-Fi 6E' },
    ],
  },
  {
    id: 'apple-iphone-15-128',
    slug: 'iphone-15-128-blue',
    brand: 'Apple',
    name: 'iPhone 15',
    heroTitle: 'Everyday flagship balance with fresh battery confidence.',
    shortDescription: 'Refined standard iPhone 15 with color-rich finish, USB-C, and all-day reliability.',
    longDescription:
      'For customers who want the clean Apple experience without stepping into Pro pricing, this iPhone 15 delivers balanced value. It combines premium condition, reliable battery health, and a presentation designed to make used tech feel elevated rather than compromised.',
    category: 'Standard',
    storage: '128GB',
    color: 'Blue',
    grade: 'A+',
    batteryHealth: 94,
    launchYear: 2023,
    price: 18990000,
    originalPrice: 24990000,
    monthlyPrice: 1583000,
    rating: 4.8,
    reviewCount: 96,
    featured: true,
    badge: 'Most balanced',
    finish: 'Color-infused glass back',
    display: '6.1-inch Super Retina XDR',
    chipset: 'A16 Bionic',
    camera: '48MP main camera',
    warranty: '12-month hardware warranty',
    stockLabel: 'Ready to ship',
    maxTradeIn: 14800000,
    gradient: 'linear-gradient(135deg, #d7e8ff 0%, #8fbaf6 48%, #3a6fb7 100%)',
    accessories: ['USB-C cable', 'QC report', 'Eject tool', 'Setup guide'],
    summaryBullets: ['Battery health 94%', 'USB-C convenience', 'Excellent paint finish'],
    highlightBullets: [
      'Strong value point for users upgrading from iPhone 11, 12, or XR.',
      'Crisp display, compact feel, and dependable day-long battery profile.',
      'Fast dispatch with quality-control card inside the box.',
    ],
    specs: [
      { label: 'Battery', value: '94% health' },
      { label: 'Security', value: 'Face ID' },
      { label: 'Port', value: 'USB-C' },
      { label: 'Build', value: 'Aluminum + glass' },
      { label: 'Camera', value: '2x optical-quality crop' },
      { label: 'Connectivity', value: '5G + Wi-Fi 6' },
    ],
  },
  {
    id: 'apple-iphone-14-pro-256',
    slug: 'iphone-14-pro-256-space-black',
    brand: 'Apple',
    name: 'iPhone 14 Pro',
    heroTitle: 'Dynamic Island era performance at a sharper used-market value.',
    shortDescription: 'Premium pre-owned iPhone 14 Pro with deep black finish and creator-grade optics.',
    longDescription:
      'This model is built for buyers who still want a distinctly premium iPhone with better value density. The camera system, stainless finish, and battery score make it a favorite for content, business travel, and customers who want a flagship feel below the latest release.',
    category: 'Pro',
    storage: '256GB',
    color: 'Space Black',
    grade: 'A',
    batteryHealth: 89,
    launchYear: 2022,
    price: 18950000,
    originalPrice: 30990000,
    monthlyPrice: 1579000,
    rating: 4.8,
    reviewCount: 84,
    featured: true,
    badge: 'Creator pick',
    finish: 'Stainless steel and textured glass',
    display: '6.1-inch Always-On OLED',
    chipset: 'A16 Bionic',
    camera: '48MP Pro camera system',
    warranty: '12-month hardware warranty',
    stockLabel: 'Low stock',
    maxTradeIn: 13600000,
    gradient: 'linear-gradient(135deg, #4a4d54 0%, #1f2228 48%, #090b0f 100%)',
    accessories: ['Lightning cable', 'QC report', 'Lens calibration sheet', 'Setup guide'],
    summaryBullets: ['Battery health 89%', 'Frame shows only hairline signs', 'Speaker and camera fully tested'],
    highlightBullets: [
      'Excellent option for photo-first buyers who want 48MP capture without current-gen pricing.',
      'Hand-checked stainless frame and polished lens rings for premium shelf appeal.',
      'Strong resale floor and high trade-in value retention.',
    ],
    specs: [
      { label: 'Battery', value: '89% health' },
      { label: 'Display', value: '120Hz ProMotion' },
      { label: 'Security', value: 'Face ID' },
      { label: 'Port', value: 'Lightning' },
      { label: 'Frame', value: 'Stainless steel' },
      { label: 'Video', value: '4K Cinematic mode' },
    ],
  },
  {
    id: 'apple-iphone-14-128',
    slug: 'iphone-14-128-starlight',
    brand: 'Apple',
    name: 'iPhone 14',
    heroTitle: 'Familiar Apple polish with one of the safest value profiles in stock.',
    shortDescription: 'Reliable iPhone 14 for users who want excellent condition and easy long-term ownership.',
    longDescription:
      'The standard iPhone 14 remains one of the easiest devices to recommend because it balances price, performance, and maintenance cost. This unit is curated for buyers who want an easy, trustworthy entry into the premium used segment.',
    category: 'Standard',
    storage: '128GB',
    color: 'Starlight',
    grade: 'A',
    batteryHealth: 90,
    launchYear: 2022,
    price: 15990000,
    originalPrice: 22990000,
    monthlyPrice: 1333000,
    rating: 4.7,
    reviewCount: 63,
    featured: true,
    badge: 'Safe choice',
    finish: 'Gloss glass with clean side rails',
    display: '6.1-inch Super Retina XDR',
    chipset: 'A15 Bionic',
    camera: 'Dual 12MP camera system',
    warranty: '12-month hardware warranty',
    stockLabel: 'Ready to ship',
    maxTradeIn: 11700000,
    gradient: 'linear-gradient(135deg, #faf8ef 0%, #e0d7c6 45%, #b8a88e 100%)',
    accessories: ['Lightning cable', 'QC report', 'SIM tool', 'Setup guide'],
    summaryBullets: ['Battery health 90%', 'Minimal wear on rails', 'Ideal for daily office and media use'],
    highlightBullets: [
      'Great fit for buyers prioritizing stability over spec chasing.',
      'Balanced pricing with predictable long-term ownership cost.',
      'Pairs well with accessories and Apple ecosystem carryover.',
    ],
    specs: [
      { label: 'Battery', value: '90% health' },
      { label: 'Security', value: 'Face ID' },
      { label: 'Frame', value: 'Aluminum' },
      { label: 'Port', value: 'Lightning' },
      { label: 'Safety', value: 'Crash Detection' },
      { label: 'Connectivity', value: '5G + eSIM ready' },
    ],
  },
  {
    id: 'apple-iphone-13-pro-256',
    slug: 'iphone-13-pro-256-sierra-blue',
    brand: 'Apple',
    name: 'iPhone 13 Pro',
    heroTitle: 'A proven Pro model for customers who care about price-to-power ratio.',
    shortDescription: 'Solid-value iPhone 13 Pro with ProMotion display and premium build.',
    longDescription:
      'The iPhone 13 Pro continues to hit a sweet spot in the used market. It keeps the stainless feel and 120Hz fluidity that still impress premium buyers, while landing at a price point that feels much easier to justify.',
    category: 'Pro',
    storage: '256GB',
    color: 'Sierra Blue',
    grade: 'A',
    batteryHealth: 88,
    launchYear: 2021,
    price: 14990000,
    originalPrice: 30990000,
    monthlyPrice: 1249000,
    rating: 4.7,
    reviewCount: 72,
    featured: false,
    badge: 'Value pro',
    finish: 'Stainless steel with matte back',
    display: '6.1-inch ProMotion OLED',
    chipset: 'A15 Bionic',
    camera: 'Triple 12MP camera system',
    warranty: '12-month hardware warranty',
    stockLabel: 'Ready to ship',
    maxTradeIn: 10200000,
    gradient: 'linear-gradient(135deg, #dbebf5 0%, #8faec9 46%, #4e6884 100%)',
    accessories: ['Lightning cable', 'QC report', 'Battery certificate', 'Setup guide'],
    summaryBullets: ['Battery health 88%', 'Strong camera stabilization', 'Premium stainless frame'],
    highlightBullets: [
      'Ideal for users moving from standard iPhone to their first Pro device.',
      'Still highly capable for social content, editing, and travel photography.',
      'Balanced performance headroom for the next few years.',
    ],
    specs: [
      { label: 'Battery', value: '88% health' },
      { label: 'Display', value: '120Hz ProMotion' },
      { label: 'Chip', value: 'A15 Bionic' },
      { label: 'Camera', value: 'Macro + Night mode' },
      { label: 'Frame', value: 'Stainless steel' },
      { label: 'Connectivity', value: '5G + MagSafe' },
    ],
  },
  {
    id: 'apple-iphone-13-128',
    slug: 'iphone-13-128-midnight',
    brand: 'Apple',
    name: 'iPhone 13',
    heroTitle: 'One of the most practical Apple renewals for students and young professionals.',
    shortDescription: 'Refined value pick with strong battery score and excellent everyday speed.',
    longDescription:
      'This is the device for buyers who want the Apple experience to feel dependable, attractive, and smartly priced. It is the kind of phone that keeps cart conversion strong because the story is easy: good condition, healthy battery, and no nonsense ownership.',
    category: 'Standard',
    storage: '128GB',
    color: 'Midnight',
    grade: 'A',
    batteryHealth: 92,
    launchYear: 2021,
    price: 12490000,
    originalPrice: 21990000,
    monthlyPrice: 1041000,
    rating: 4.7,
    reviewCount: 110,
    featured: false,
    badge: 'Best value',
    finish: 'Dark aluminum frame',
    display: '6.1-inch Super Retina XDR',
    chipset: 'A15 Bionic',
    camera: 'Dual 12MP wide and ultra wide',
    warranty: '12-month hardware warranty',
    stockLabel: 'Ready to ship',
    maxTradeIn: 8900000,
    gradient: 'linear-gradient(135deg, #3f4450 0%, #1c2129 46%, #090b10 100%)',
    accessories: ['Lightning cable', 'QC report', 'Screen check card', 'Setup guide'],
    summaryBullets: ['Battery health 92%', 'Excellent value retention', 'Very low cosmetic wear'],
    highlightBullets: [
      'A strong first Apple purchase for price-sensitive premium buyers.',
      'High confidence battery score removes one of the main used-phone objections.',
      'Compact enough for one-hand use while still feeling current.',
    ],
    specs: [
      { label: 'Battery', value: '92% health' },
      { label: 'Chip', value: 'A15 Bionic' },
      { label: 'Security', value: 'Face ID' },
      { label: 'Port', value: 'Lightning' },
      { label: 'Charging', value: 'MagSafe support' },
      { label: 'Connectivity', value: '5G + dual eSIM' },
    ],
  },
  {
    id: 'samsung-galaxy-s24-256',
    slug: 'galaxy-s24-256-onyx-black',
    brand: 'Samsung',
    name: 'Galaxy S24',
    heroTitle: 'Compact Android flagship with sharp resale quality and modern AI feature set.',
    shortDescription: 'Premium Android option for shoppers who want flagship polish beyond the Apple ecosystem.',
    longDescription:
      'A serious used-phone catalog should not stop at iPhone. The Galaxy S24 gives the store a strong premium Android narrative, especially for users who want AI tools, a compact body, and a device that still feels current inside a luxury-style storefront.',
    category: 'Android flagship',
    storage: '256GB',
    color: 'Onyx Black',
    grade: 'A+',
    batteryHealth: 95,
    launchYear: 2024,
    price: 17990000,
    originalPrice: 22990000,
    monthlyPrice: 1499000,
    rating: 4.8,
    reviewCount: 41,
    featured: false,
    badge: 'Android premium',
    finish: 'Armor aluminum frame',
    display: '6.2-inch Dynamic AMOLED 2X',
    chipset: 'Snapdragon 8 Gen 3',
    camera: '50MP main + 3x tele',
    warranty: '12-month hardware warranty',
    stockLabel: 'New arrival',
    maxTradeIn: 12900000,
    gradient: 'linear-gradient(135deg, #585b63 0%, #262931 46%, #0c0d11 100%)',
    accessories: ['USB-C cable', 'QC report', 'Display test card', 'Setup guide'],
    summaryBullets: ['Battery health 95%', 'Excellent OLED condition', 'Current-generation Android flagship'],
    highlightBullets: [
      'Makes the catalog feel broader and more premium without losing curation.',
      'Great option for camera-first Android users and compact-phone fans.',
      'High-condition unit suitable for merchandising in the hero grid.',
    ],
    specs: [
      { label: 'Battery', value: '95% health' },
      { label: 'Display', value: '1-120Hz LTPO AMOLED' },
      { label: 'Chip', value: 'Snapdragon 8 Gen 3' },
      { label: 'Camera', value: '50MP main + 30x space zoom' },
      { label: 'Security', value: 'Ultrasonic fingerprint' },
      { label: 'Charging', value: 'USB-C + wireless charging' },
    ],
  },
  {
    id: 'google-pixel-8-pro-128',
    slug: 'pixel-8-pro-128-bay-blue',
    brand: 'Google',
    name: 'Pixel 8 Pro',
    heroTitle: 'Editorial camera quality and clean software for buyers who want something more distinct.',
    shortDescription: 'Curated Pixel flagship with standout camera processing and clean Android software.',
    longDescription:
      'Pixel adds a more design-forward, photography-led option to the store. It is useful for building a premium multi-brand narrative while keeping the overall experience calm, refined, and confidence-heavy.',
    category: 'Android flagship',
    storage: '128GB',
    color: 'Bay Blue',
    grade: 'A',
    batteryHealth: 93,
    launchYear: 2023,
    price: 16990000,
    originalPrice: 26990000,
    monthlyPrice: 1416000,
    rating: 4.7,
    reviewCount: 29,
    featured: false,
    badge: 'Photo first',
    finish: 'Polished aluminum camera bar',
    display: '6.7-inch LTPO OLED',
    chipset: 'Google Tensor G3',
    camera: '50MP main + 5x tele',
    warranty: '12-month hardware warranty',
    stockLabel: 'Ready to ship',
    maxTradeIn: 11800000,
    gradient: 'linear-gradient(135deg, #d9eef2 0%, #6ca6c7 46%, #1f5068 100%)',
    accessories: ['USB-C cable', 'QC report', 'Camera alignment sheet', 'Setup guide'],
    summaryBullets: ['Battery health 93%', 'Excellent camera bar finish', 'AI tools tested and active'],
    highlightBullets: [
      'Ideal for shoppers who prioritize computational photography.',
      'Adds visual variety and premium depth to the storefront.',
      'Pairs strong used-market pricing with a distinctive design story.',
    ],
    specs: [
      { label: 'Battery', value: '93% health' },
      { label: 'Display', value: 'LTPO 1-120Hz OLED' },
      { label: 'Chip', value: 'Tensor G3' },
      { label: 'Camera', value: '5x optical telephoto' },
      { label: 'Security', value: 'Face unlock + fingerprint' },
      { label: 'Charging', value: 'USB-C + wireless charging' },
    ],
  },
]
